version: "3.7"

services:
  redis:
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - internal
  
  kaldi-worker:
    image: docker-kaldi-gstreamer
    expose:
      - "80"
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - "~/Documents/politie/gdas/docker-kaldi-gstreamer/models:/opt/models"
    
networks:
  internal:
    driver_opts:
      internal: "true"
    driver: "bridge"
